name: Docker Run Action Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  result_code_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test that the action is returning a zero exit code
      uses: ./
      id: run-docker
      with:
        environment_image: alpine:3.16.2
        command: echo "::set-output name=alpine-version::`cat /etc/alpine-release`"
    - name: Test the output
      uses: actions/github-script@v3
      with:
        script: |
          const resultCode = '${{ steps.run-docker.outputs.result_code }}';
          if (resultCode !== '0') {
            core.setFailed(`result_code_test Failed`);
          }
  pipeline_artifacts_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test that the action is returning a zero exit code
      uses: ./
      id: run-docker
      with:
        environment_image: alpine:3.16.2
        command: echo "my new build !@#$%^&*()_+{}[]" > build.txt
    - name: Test the output
      uses: actions/github-script@v3
      with:
        script: |
          const resultCode = '${{ steps.run-docker.outputs.pipeline_artifacts }}';
          if (resultCode !== '0') {
            core.setFailed(`pipeline_artifacts_test Failed`);
          }